plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':core')

    testImplementation "junit:junit:4.13.2"
    testImplementation "com.google.truth:truth:1.4.0"
}

application {
    mainClass = 'se.whitchurch.nordict.cli.MainKt'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}