plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':core')
}

application {
    mainClass = 'se.whitchurch.nordict.cli.MainKt'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}