plugins {
    id 'org.jetbrains.kotlin.jvm'
}

repositories {
    mavenCentral()
}

dependencies {
    api "org.jsoup:jsoup:1.12.1"
    api "com.google.code.gson:gson:2.10.1"
    api "com.squareup.okhttp3:okhttp:4.9.1"

    testImplementation "junit:junit:4.13.2"
    testImplementation "com.google.truth:truth:1.0"
    testImplementation "com.squareup.okhttp3:mockwebserver:4.9.1"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

test {
    testLogging {
        events "failed", "skipped"
    }
}